# Generated by Django 5.2.11 on 2026-03-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_story_caption_story_music_story_tagged_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='story_audio/'),
        ),
    ]
