# Generated by Django 5.2.11 on 2026-03-08 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_story_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='audio_start',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
