# Generated by Django 5.2.11 on 2026-03-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_notification_story_story_audio_end_story_audio_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='story',
        ),
        migrations.RemoveField(
            model_name='story',
            name='audio_end',
        ),
        migrations.RemoveField(
            model_name='story',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='story',
            name='audio_start',
        ),
        migrations.RemoveField(
            model_name='story',
            name='likes',
        ),
        migrations.AddField(
            model_name='story',
            name='music_artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='music_coverart',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='music_start_time',
            field=models.IntegerField(default=0, help_text='Start time in seconds for the trimmed 15s clip'),
        ),
        migrations.AddField(
            model_name='story',
            name='music_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='music_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
