# Generated by Django 5.2.11 on 2026-03-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_notification_story_remove_story_audio_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='music',
        ),
        migrations.AlterField(
            model_name='story',
            name='music_artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='music_coverart',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='music_start_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='story',
            name='music_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='music_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
