# Generated by Django 5.2.11 on 2026-03-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_message_story_reply_notification_story_story_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='caption_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='story',
            name='caption_y',
            field=models.FloatField(default=0.8),
        ),
    ]
