# Generated by Django 5.2.11 on 2026-03-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_profile_date_of_birth_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='LoginActivity',
        ),
    ]
