# Generated by Django 5.2.11 on 2026-03-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_profile_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='music_duration',
            field=models.FloatField(default=15.0),
        ),
    ]
