# Generated by Django 5.2.11 on 2026-03-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_loginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='music_artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='music_coverart',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='music_duration',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='post',
            name='music_start_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='post',
            name='music_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='music_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
