# Generated by Django 4.2 on 2026-03-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_post_music_artist_post_music_coverart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='posts.post'),
        ),
    ]
