"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--!zn%m1y3rsue6ve$ssxft!i6g#xvf-ed$loqaby^od%zgu4#+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['testserver', '127.0.0.1', 'localhost', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'posts',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import os
import socket
import pymysql
from pathlib import Path
from urllib.parse import urlparse

db_url = os.environ.get('MYSQL_URL') or os.environ.get('MYSQL_PRIVATE_URL') or os.environ.get('DATABASE_URL')
mysql_host = os.environ.get('MYSQL_HOST') or os.environ.get('MYSQLHOST')

# Clean up literal unexpanded Railway template syntax (${...})
if mysql_host and "${" in mysql_host:
    mysql_host = None
if db_url and "${" in db_url:
    db_url = None

def is_mysql_available(host, user, password, db, port=3306):
    try:
        socket.gethostbyname(host)
        conn = pymysql.connect(
            host=host,
            user=user,
            password=password,
            database=db,
            port=int(port),
            connect_timeout=1
        )
        conn.close()
        return True
    except Exception:
        return False

use_mysql = False
mysql_config = {}

if db_url and db_url.startswith('mysql'):
    try:
        parsed = urlparse(db_url)
        h = parsed.hostname
        u = parsed.username or 'root'
        p = parsed.password or ''
        d = parsed.path.lstrip('/') or 'railway'
        pt = parsed.port or 3306
        if h and is_mysql_available(h, u, p, d, pt):
            use_mysql = True
            mysql_config = {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': d,
                'USER': u,
                'PASSWORD': p,
                'HOST': h,
                'PORT': str(pt),
                'OPTIONS': {'charset': 'utf8mb4'},
            }
    except Exception:
        use_mysql = False

if not use_mysql and mysql_host:
    port = os.environ.get('MYSQL_PORT') or os.environ.get('MYSQLPORT') or '3306'
    user = os.environ.get('MYSQL_USER') or os.environ.get('MYSQLUSER') or 'root'
    password = os.environ.get('MYSQL_PASSWORD') or os.environ.get('MYSQLPASSWORD') or ''
    database = os.environ.get('MYSQL_NAME') or os.environ.get('MYSQLDATABASE') or 'railway'
    if is_mysql_available(mysql_host, user, password, database, port):
        use_mysql = True
        mysql_config = {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': database,
            'USER': user,
            'PASSWORD': password,
            'HOST': mysql_host,
            'PORT': str(port),
            'OPTIONS': {'charset': 'utf8mb4'},
        }

if use_mysql:
    DATABASES = {'default': mysql_config}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}
